[package]
name = "handover-ipc"
version = "0.3.2"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Client/server IPC protocol for Handover"

[dependencies]
handover-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
