[workspace]
resolver = "3"
members = [
    "crates/handover-core",
    "crates/handover-kdeconnect",
    "crates/handover-native",
    "crates/handover-gmessages",
    "crates/handover-ipc",
    "handoverd",
    "handoverctl",
]

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
clap_mangen = "0.2"
handover-core = { version = "0.3.3", path = "crates/handover-core" }
handover-gmessages = { version = "0.3.3", path = "crates/handover-gmessages" }
handover-ipc = { version = "0.3.3", path = "crates/handover-ipc" }
handover-kdeconnect = { version = "0.3.3", path = "crates/handover-kdeconnect" }
handover-native = { version = "0.3.3", path = "crates/handover-native" }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
url = "2.5"
tempfile = "3.27"
tokio = { version = "1.47", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zbus = { version = "5.13", default-features = false, features = ["tokio"] }
