[package]
name = "handoverd"
version = "0.3.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Handover daemon"

[dependencies]
handover-core.workspace = true
handover-gmessages.workspace = true
handover-ipc.workspace = true
handover-kdeconnect.workspace = true
handover-native.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
