#!/usr/bin/env python3
"""Install the local Chrome Native Messaging launcher for the auth probe."""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import stat
import sys
import tempfile
from pathlib import Path


HOST_NAME = "com.handover.google_messages.auth_probe"
LAUNCHER_MARKER = "# Generated by Handover Google Messages auth probe installer.\n"
DEFAULT_EXTENSION_DIR = Path(__file__).resolve().parent / "chrome-observer"
EXISTING_FILE_LIMIT = 64 * 1024


class InstallError(Exception):
    """A fixed installer failure code safe to print to stderr."""


def valid_extension_id(value: str) -> bool:
    return len(value) == 32 and all("a" <= char <= "p" for char in value)


def extension_id_for(directory: Path) -> str:
    try:
        canonical = directory.resolve(strict=True)
        if not canonical.is_dir():
            raise InstallError("invalid_extension_directory")
        digest = hashlib.sha256(str(canonical).encode("utf-8")).digest()[:16]
    except OSError as exc:
        raise InstallError("invalid_extension_directory") from exc
    return "".join(chr(ord("a") + nibble) for byte in digest for nibble in (byte >> 4, byte & 0x0F))


def validate_binary(binary: Path) -> Path:
    if not binary.is_absolute():
        raise InstallError("binary_must_be_absolute")
    try:
        metadata = binary.lstat()
    except OSError as exc:
        raise InstallError("invalid_binary") from exc
    if not stat.S_ISREG(metadata.st_mode) or not os.access(binary, os.X_OK):
        raise InstallError("invalid_binary")
    try:
        return binary.resolve(strict=True)
    except OSError as exc:
        raise InstallError("invalid_binary") from exc


def _private_directory(path: Path) -> None:
    try:
        path.mkdir(mode=0o700, parents=True, exist_ok=True)
        metadata = path.lstat()
        if not stat.S_ISDIR(metadata.st_mode):
            raise InstallError("unsafe_install_directory")
        path.chmod(0o700)
    except OSError as exc:
        raise InstallError("install_directory_error") from exc


def _owned_existing_file(path: Path, ownership: str) -> bool:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise InstallError("install_file_error") from exc
    if not stat.S_ISREG(metadata.st_mode):
        raise InstallError("unrelated_existing_file")
    if metadata.st_size > EXISTING_FILE_LIMIT:
        raise InstallError("unrelated_existing_file")
    try:
        with path.open("rb") as stream:
            data = stream.read(EXISTING_FILE_LIMIT + 1)
    except OSError as exc:
        raise InstallError("install_file_error") from exc
    if len(data) > EXISTING_FILE_LIMIT:
        raise InstallError("unrelated_existing_file")
    if ownership == "launcher":
        return data.startswith(("#!/bin/sh\n" + LAUNCHER_MARKER).encode("utf-8"))
    try:
        manifest = json.loads(data)
    except (UnicodeDecodeError, json.JSONDecodeError):
        return False
    return isinstance(manifest, dict) and manifest.get("name") == HOST_NAME


def _atomic_write(path: Path, data: bytes, mode: int, ownership: str) -> None:
    exists = _check_target(path, ownership)
    fd, temp_name = tempfile.mkstemp(prefix=".handover-tmp-", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        if exists:
            os.replace(temp_path, path)
        else:
            os.link(temp_path, path)
            temp_path.unlink()
    except OSError as exc:
        raise InstallError("install_file_error") from exc
    finally:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass


def _check_target(path: Path, ownership: str) -> bool:
    exists = path.exists() or path.is_symlink()
    if exists and path.is_symlink():
        raise InstallError("unrelated_existing_file")
    if exists and not _owned_existing_file(path, ownership):
        raise InstallError("unrelated_existing_file")
    return exists


def install(binary: Path, extension_dir: Path, extension_override: str | None = None) -> tuple[str, Path, Path]:
    executable = validate_binary(Path(binary))
    computed_id = extension_id_for(Path(extension_dir))
    extension_id = computed_id if extension_override is None else extension_override
    if not valid_extension_id(extension_id):
        raise InstallError("invalid_extension_id")

    home = Path.home()
    launcher_dir = home / ".local" / "lib" / "handover" / "google-messages-auth-probe"
    config_home_value = os.environ.get("XDG_CONFIG_HOME")
    config_home = Path(config_home_value) if config_home_value else home / ".config"
    if not config_home.is_absolute():
        raise InstallError("invalid_config_directory")
    host_dir = config_home / "google-chrome" / "NativeMessagingHosts"
    _private_directory(launcher_dir)
    _private_directory(host_dir)

    launcher = launcher_dir / "launch-auth-probe"
    manifest_path = host_dir / f"{HOST_NAME}.json"
    launcher_text = (
        "#!/bin/sh\n"
        + LAUNCHER_MARKER
        + "exec "
        + shlex.quote(str(executable))
        + " --allowed-extension-id "
        + shlex.quote(extension_id)
        + ' "$@"\n'
    )
    manifest = {
        "name": HOST_NAME,
        "description": "Handover Google Messages authentication probe",
        "path": str(launcher),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{extension_id}/"],
    }
    manifest_data = (json.dumps(manifest, indent=2) + "\n").encode("utf-8")
    _check_target(launcher, "launcher")
    _check_target(manifest_path, "manifest")
    _atomic_write(launcher, launcher_text.encode("utf-8"), 0o700, "launcher")
    _atomic_write(manifest_path, manifest_data, 0o600, "manifest")
    return extension_id, launcher, manifest_path


def _parse_args(argv: list[str]) -> tuple[Path, Path, str | None]:
    options: dict[str, str] = {}
    index = 0
    while index < len(argv):
        name = argv[index]
        if name not in {"--binary", "--extension-dir", "--extension-id"} or name in options:
            raise InstallError("invalid_arguments")
        index += 1
        if index >= len(argv):
            raise InstallError("invalid_arguments")
        options[name] = argv[index]
        index += 1
    if "--binary" not in options:
        raise InstallError("invalid_arguments")
    return (
        Path(options["--binary"]),
        Path(options.get("--extension-dir", str(DEFAULT_EXTENSION_DIR))),
        options.get("--extension-id"),
    )


def main(argv: list[str] | None = None) -> int:
    try:
        binary, extension_dir, extension_override = _parse_args(
            sys.argv[1:] if argv is None else argv
        )
        extension_id, launcher, manifest = install(binary, extension_dir, extension_override)
    except InstallError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"extension_id={extension_id}")
    print(f"launcher={launcher}")
    print(f"manifest={manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
