# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_handoverctl_global_optspecs
    string join \n h/help V/version
end

function __fish_handoverctl_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_handoverctl_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_handoverctl_using_subcommand
    set -l cmd (__fish_handoverctl_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c handoverctl -n "__fish_handoverctl_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -s V -l version -d 'Print version'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "devices" -d 'List native devices known to handoverd'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "native" -d 'Inspect and manage native Android pairing and device commands'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "notifications" -d 'List active remote notifications from the daemon snapshot'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "contacts" -d 'List or request an on-demand native contacts snapshot'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "media" -d 'List media sessions, or send one playback command'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "monitor" -d 'Print live normalized device and notification changes'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "send-url" -d 'Send a URL to one paired device'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "notify" -d 'Send a notification to one native phone'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "clipboard" -d 'Set the clipboard on one native phone'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "send-file" -d 'Send one local file to a paired device'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "screensaver" -d 'Control the desktop idle inhibitor: inhibit, release, or follow'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "clipboard-mirror" -d 'Get or set Linux-to-phone background clipboard mirroring (off by default)'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "clipboard-history" -d 'List, pin, copy, and clear phone-to-Linux clipboard history'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "cancel-share" -d 'Cancel a queued native share that has not started streaming'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "custom" -d 'List or run allowlisted desktop commands'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "calls" -d 'Print current normalized call state for one device'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "messages" -d 'Inspect and use messaging accounts and conversations'
complete -c handoverctl -n "__fish_handoverctl_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand devices" -l include-compatibility -d 'Include devices supplied by the optional KDE Connect backend'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand devices" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "peers" -d 'List trusted native peers (id, name, certificate fingerprint)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "pending" -d 'List pending pairing requests (id, name, eight-digit code)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "pair" -d 'Approve a pending pairing request after comparing codes'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "unpair" -d 'Revoke a trusted native peer'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "ping" -d 'Send a user-visible liveness ping to a native device name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "ring" -d 'Ring and vibrate a native device selected by name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "lock" -d 'Lock a native phone when device-admin access is enabled'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "keep-awake" -d 'Ask a native phone to hold its wake lock (or release it with --release)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "tethering" -d 'Ask a native phone to open its tethering settings screen'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "filesystem-list" -d 'Ask the phone for a bounded directory listing. Results arrive through `monitor` because the native transfer is asynchronous'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "call" -d 'Send a call control action to a native phone'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and not __fish_seen_subcommand_from peers pending pair unpair ping ring lock keep-awake tethering filesystem-list call help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from peers" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from pending" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from pair" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from unpair" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from ping" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from ring" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from lock" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from keep-awake" -l release -d 'Release the phone wake lock instead of holding it'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from keep-awake" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from tethering" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from filesystem-list" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from call" -l confirm -d 'Explicitly authorize placing a real phone call (required for place)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from call" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "peers" -d 'List trusted native peers (id, name, certificate fingerprint)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "pending" -d 'List pending pairing requests (id, name, eight-digit code)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "pair" -d 'Approve a pending pairing request after comparing codes'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "unpair" -d 'Revoke a trusted native peer'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "ping" -d 'Send a user-visible liveness ping to a native device name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "ring" -d 'Ring and vibrate a native device selected by name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "lock" -d 'Lock a native phone when device-admin access is enabled'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "keep-awake" -d 'Ask a native phone to hold its wake lock (or release it with --release)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "tethering" -d 'Ask a native phone to open its tethering settings screen'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "filesystem-list" -d 'Ask the phone for a bounded directory listing. Results arrive through `monitor` because the native transfer is asynchronous'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "call" -d 'Send a call control action to a native phone'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand native; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand notifications" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and not __fish_seen_subcommand_from list sync help" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and not __fish_seen_subcommand_from list sync help" -f -a "list" -d 'List the latest contacts snapshot held by handoverd'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and not __fish_seen_subcommand_from list sync help" -f -a "sync" -d 'Ask one native phone to send a fresh contacts snapshot'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and not __fish_seen_subcommand_from list sync help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and __fish_seen_subcommand_from help" -f -a "list" -d 'List the latest contacts snapshot held by handoverd'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Ask one native phone to send a fresh contacts snapshot'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand contacts; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "play" -d 'Start playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "pause" -d 'Pause playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "play-pause" -d 'Toggle playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "next" -d 'Skip to the next item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "previous" -d 'Return to the previous item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and not __fish_seen_subcommand_from play pause play-pause next previous help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from play" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from pause" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from play-pause" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from next" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from previous" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "play" -d 'Start playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "pause" -d 'Pause playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "play-pause" -d 'Toggle playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "next" -d 'Skip to the next item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "previous" -d 'Return to the previous item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand monitor" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand send-url" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand notify" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand send-file" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand screensaver" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-mirror" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "list" -d 'List recent and pinned entries (text previews only)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "save" -d 'Save a new pinned string'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "pin" -d 'Pin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "unpin" -d 'Unpin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "copy" -d 'Copy an entry into the Linux clipboard'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "clear" -d 'Remove recent entries, retaining pins unless --all is passed'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and not __fish_seen_subcommand_from list save pin unpin copy clear help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from save" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from pin" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from unpin" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from copy" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from clear" -l all -d 'Also remove pinned entries'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from clear" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "list" -d 'List recent and pinned entries (text previews only)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "save" -d 'Save a new pinned string'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "pin" -d 'Pin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "unpin" -d 'Unpin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "copy" -d 'Copy an entry into the Linux clipboard'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "clear" -d 'Remove recent entries, retaining pins unless --all is passed'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand clipboard-history; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand cancel-share" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and not __fish_seen_subcommand_from list run help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and not __fish_seen_subcommand_from list run help" -f -a "list" -d 'List allowlisted desktop commands with their fixed argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and not __fish_seen_subcommand_from list run help" -f -a "run" -d 'Run one allowlisted desktop command by name'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and not __fish_seen_subcommand_from list run help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and __fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and __fish_seen_subcommand_from help" -f -a "list" -d 'List allowlisted desktop commands with their fixed argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and __fish_seen_subcommand_from help" -f -a "run" -d 'Run one allowlisted desktop command by name'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand custom; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand calls" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "accounts" -d 'List messaging accounts with connection state'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "conversations" -d 'List conversations for one account'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "history" -d 'Show message history for one conversation (ACCOUNT:THREAD or THREAD)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "send" -d 'Send a text message (accepted, not delivered)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "send-file" -d 'Send a file attachment with an optional caption'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "reply" -d 'Reply to a message (ACCOUNT:THREAD:MESSAGE or THREAD:MESSAGE ...)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "react" -d 'Add a reaction to a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "unreact" -d 'Remove a reaction from a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "read" -d 'Mark a conversation read (optionally up to one message)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "typing" -d 'Send a typing-start ping (no typing-stop exists upstream)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "delete" -d 'Delete one own message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "open" -d 'Open or create a conversation with addresses (phone numbers/emails)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "login" -d 'Log in: read a credential bundle from a file or stdin, never argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "logout" -d 'Log out and revoke helper access'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "sync" -d 'Ask the helper to re-emit authoritative state for one account'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and not __fish_seen_subcommand_from accounts conversations history send send-file reply react unreact read typing delete open login logout sync help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from accounts" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from conversations" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from history" -l limit -d 'Maximum messages to show' -r
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from history" -l cursor -d 'Cursor printed by a previous history page' -r
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from history" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from send" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from send-file" -l caption -d 'Optional caption sent with the attachment' -r
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from send-file" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from reply" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from react" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from unreact" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from read" -l message -d 'Message selector marking the read point' -r
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from read" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from typing" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from open" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from login" -l from-file -d 'Read the credential bundle from PATH instead of stdin' -r -F
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from logout" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "accounts" -d 'List messaging accounts with connection state'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "conversations" -d 'List conversations for one account'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "history" -d 'Show message history for one conversation (ACCOUNT:THREAD or THREAD)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "send" -d 'Send a text message (accepted, not delivered)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "send-file" -d 'Send a file attachment with an optional caption'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "reply" -d 'Reply to a message (ACCOUNT:THREAD:MESSAGE or THREAD:MESSAGE ...)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "react" -d 'Add a reaction to a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "unreact" -d 'Remove a reaction from a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "read" -d 'Mark a conversation read (optionally up to one message)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "typing" -d 'Send a typing-start ping (no typing-stop exists upstream)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete one own message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "open" -d 'Open or create a conversation with addresses (phone numbers/emails)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "login" -d 'Log in: read a credential bundle from a file or stdin, never argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "logout" -d 'Log out and revoke helper access'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Ask the helper to re-emit authoritative state for one account'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand messages; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "devices" -d 'List native devices known to handoverd'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "native" -d 'Inspect and manage native Android pairing and device commands'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "notifications" -d 'List active remote notifications from the daemon snapshot'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "contacts" -d 'List or request an on-demand native contacts snapshot'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "media" -d 'List media sessions, or send one playback command'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "monitor" -d 'Print live normalized device and notification changes'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "send-url" -d 'Send a URL to one paired device'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "notify" -d 'Send a notification to one native phone'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "clipboard" -d 'Set the clipboard on one native phone'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "send-file" -d 'Send one local file to a paired device'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "screensaver" -d 'Control the desktop idle inhibitor: inhibit, release, or follow'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "clipboard-mirror" -d 'Get or set Linux-to-phone background clipboard mirroring (off by default)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "clipboard-history" -d 'List, pin, copy, and clear phone-to-Linux clipboard history'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "cancel-share" -d 'Cancel a queued native share that has not started streaming'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "custom" -d 'List or run allowlisted desktop commands'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "calls" -d 'Print current normalized call state for one device'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "messages" -d 'Inspect and use messaging accounts and conversations'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and not __fish_seen_subcommand_from devices native notifications contacts media monitor send-url notify clipboard send-file screensaver clipboard-mirror clipboard-history cancel-share custom calls messages help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "peers" -d 'List trusted native peers (id, name, certificate fingerprint)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "pending" -d 'List pending pairing requests (id, name, eight-digit code)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "pair" -d 'Approve a pending pairing request after comparing codes'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "unpair" -d 'Revoke a trusted native peer'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "ping" -d 'Send a user-visible liveness ping to a native device name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "ring" -d 'Ring and vibrate a native device selected by name or ID'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "lock" -d 'Lock a native phone when device-admin access is enabled'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "keep-awake" -d 'Ask a native phone to hold its wake lock (or release it with --release)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "tethering" -d 'Ask a native phone to open its tethering settings screen'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "filesystem-list" -d 'Ask the phone for a bounded directory listing. Results arrive through `monitor` because the native transfer is asynchronous'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from native" -f -a "call" -d 'Send a call control action to a native phone'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from contacts" -f -a "list" -d 'List the latest contacts snapshot held by handoverd'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from contacts" -f -a "sync" -d 'Ask one native phone to send a fresh contacts snapshot'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "play" -d 'Start playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "pause" -d 'Pause playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "play-pause" -d 'Toggle playback on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "next" -d 'Skip to the next item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "previous" -d 'Return to the previous item on one session'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "list" -d 'List recent and pinned entries (text previews only)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "save" -d 'Save a new pinned string'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "pin" -d 'Pin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "unpin" -d 'Unpin an existing entry by id'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "copy" -d 'Copy an entry into the Linux clipboard'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from clipboard-history" -f -a "clear" -d 'Remove recent entries, retaining pins unless --all is passed'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from custom" -f -a "list" -d 'List allowlisted desktop commands with their fixed argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from custom" -f -a "run" -d 'Run one allowlisted desktop command by name'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "accounts" -d 'List messaging accounts with connection state'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "conversations" -d 'List conversations for one account'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "history" -d 'Show message history for one conversation (ACCOUNT:THREAD or THREAD)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "send" -d 'Send a text message (accepted, not delivered)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "send-file" -d 'Send a file attachment with an optional caption'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "reply" -d 'Reply to a message (ACCOUNT:THREAD:MESSAGE or THREAD:MESSAGE ...)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "react" -d 'Add a reaction to a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "unreact" -d 'Remove a reaction from a message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "read" -d 'Mark a conversation read (optionally up to one message)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "typing" -d 'Send a typing-start ping (no typing-stop exists upstream)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "delete" -d 'Delete one own message'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "open" -d 'Open or create a conversation with addresses (phone numbers/emails)'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "login" -d 'Log in: read a credential bundle from a file or stdin, never argv'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "logout" -d 'Log out and revoke helper access'
complete -c handoverctl -n "__fish_handoverctl_using_subcommand help; and __fish_seen_subcommand_from messages" -f -a "sync" -d 'Ask the helper to re-emit authoritative state for one account'
