//! Observed Gaia revision-1 key derivation using established HKDF and SHA-256.

use hkdf::Hkdf;
use sha2::{Digest, Sha256};
use std::fmt;
use zeroize::{Zeroize, Zeroizing};

use super::HandshakeError;

const D2D_SALT: [u8; 32] = [
    130, 170, 85, 160, 211, 151, 248, 131, 70, 202, 28, 238, 141, 57, 9, 185, 95, 19, 250, 125,
    235, 29, 74, 179, 131, 118, 184, 37, 109, 168, 85, 16,
];

/// Private keys have no serialization or export API. Deriving them does not
/// establish a working channel or attest messaging capabilities.
pub(super) struct GaiaKeys {
    _first: Zeroizing<[u8; 32]>,
    _second: Zeroizing<[u8; 32]>,
}

impl fmt::Debug for GaiaKeys {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("GaiaKeys { redacted }")
    }
}

impl GaiaKeys {
    pub(super) fn derive(next: &[u8; 32]) -> Result<Self, HandshakeError> {
        let client = expand(next, &D2D_SALT, b"client")?;
        let server = expand(next, &D2D_SALT, b"server")?;
        // Xna/Vna orders Java-style signed-byte hashes, with wrapping i32
        // arithmetic. Equal hashes select the server first, as observed.
        let (first, second) = if signed_hash(&client) < signed_hash(&server) {
            (&client, &server)
        } else {
            (&server, &client)
        };
        let mut combined = Zeroizing::new([0; 96]);
        combined[..32].copy_from_slice(&D2D_SALT);
        combined[32..64].copy_from_slice(first.as_slice());
        combined[64..].copy_from_slice(second.as_slice());
        let mut digest = Sha256::digest(combined.as_slice());
        let mut base = Zeroizing::new([0; 32]);
        base.copy_from_slice(&digest);
        digest.as_mut_slice().zeroize();
        Ok(Self {
            _first: expand(base.as_slice(), b"Ditto salt 1", b"Ditto info 1")?,
            _second: expand(base.as_slice(), b"Ditto salt 2", b"Ditto info 2")?,
        })
    }
}

fn expand(key: &[u8], salt: &[u8], info: &[u8]) -> Result<Zeroizing<[u8; 32]>, HandshakeError> {
    let mut output = Zeroizing::new([0; 32]);
    Hkdf::<Sha256>::new(Some(salt), key)
        .expand(info, output.as_mut())
        .map_err(|_| HandshakeError::DerivationFailed)?;
    Ok(output)
}

fn signed_hash(bytes: &[u8; 32]) -> i32 {
    bytes.iter().fold(1i32, |hash, byte| {
        hash.wrapping_mul(31).wrapping_add(*byte as i8 as i32)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn from_hex(value: &str) -> Vec<u8> {
        value
            .as_bytes()
            .chunks_exact(2)
            .map(|pair| u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap())
            .collect()
    }

    #[test]
    fn matches_independent_webcrypto_vectors_with_both_signed_orderings() {
        // Synthetic input vectors generated by an independently authored Node
        // WebCrypto calculation of the observed Ona/Xna/q5a contract.
        for (start, first, second) in [
            (
                0u8,
                "5f6ce79dd48af3453f7f24e53268537f7a5962870144de1a52f9ed25765d3a43",
                "3b0ea4399b37c190dcb52cc976d879424c2713e4b59cdde1b77f84340194c37e",
            ),
            (
                128,
                "3fc0379d8aff9c67759cced0795e483c9e0266d5dbfd3441a7c97e986bc308dc",
                "4ffb07a511973072b0c8c0057211a8e158380e474d4b5f5fb5a7b7035e088d35",
            ),
            (
                255,
                "20c3822a732bb5c00e7be88544eae7007c1973d87b2a32051b4fdd74e0c00c32",
                "5a61279c8ba734b72e4570d9322957ebb9b7aa0f3f2185b66d3c16328a33cfc7",
            ),
        ] {
            let next = std::array::from_fn(|i| start.wrapping_add(i as u8));
            let keys = GaiaKeys::derive(&next).unwrap();
            assert!(keys._first.as_slice() == from_hex(first));
            assert!(keys._second.as_slice() == from_hex(second));
            assert_eq!(format!("{keys:?}"), "GaiaKeys { redacted }");
        }
    }
}
